#!/bin/bash

# omarchy:summary=Restart the PipeWire audio service to fix audio issues or apply new configuration.

echo -e "Restarting pipewire audio service...\n"
systemctl --user restart pipewire.service
