#!/bin/bash

# Modified from Omarchy scripts
# https://github.com/basecamp/omarchy.git

# omarchy:summary=Reload supported terminal emulators after config changes

if [[ -f ~/.config/alacritty/alacritty.toml ]]; then
  touch ~/.config/alacritty/alacritty.toml
fi

if pgrep -x kitty >/dev/null; then
  killall -SIGUSR1 kitty >/dev/null
fi

if pgrep -x ghostty >/dev/null; then
  killall -SIGUSR2 ghostty
fi

if pgrep -x foot >/dev/null; then
  killall -SIGUSR1 foot >/dev/null
fi
