#!/bin/bash

# Modified from Omarchy scripts
# https://github.com/basecamp/omarchy.git

# omarchy:summary=Set the current background image
# omarchy:args=<path-to-image>
# omarchy:examples=omarchy theme bg set ~/Pictures/wallpaper.png

if [[ -z $1 ]]; then
  echo "Usage: yomatta-theme-bg-set <path-to-image>" >&2
  exit 1
fi

BACKGROUND="$1"
CURRENT_BACKGROUND_LINK="$HOME/.config/themes/_current/background"

# Create symlink to the new background
ln -nsf "$BACKGROUND" "$CURRENT_BACKGROUND_LINK"

# Kill existing swaybg and start new one
pkill -x swaybg

# Re-launch swaybg (depending on window manager being used)

# Niri

# Mango
swaybg -i "$CURRENT_BACKGROUND_LINK" -m fill >/dev/null 2>&1 &

# Hyprland
setsid uwsm-app -- swaybg -i "$CURRENT_BACKGROUND_LINK" -m fill >/dev/null 2>&1 &
