foreground   #f0c2ac
background   #111022
cursor       #f0c2ac

color0       #111022
color8       #a88778
color1       #704F6A
color9       #704F6A
color2       #863D4E
color10      #863D4E
color3       #9E5B5E
color11      #9E5B5E
color4       #8E5468
color12      #8E5468
color5       #AC5A67
color13      #AC5A67
color6       #DA6A68
color14      #DA6A68
color7       #f0c2ac
color15      #f0c2ac
