# More option see https://github.com/DreamMaoMao/mango/wiki/

# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# keyboard rule to swap alt and SUPER key
xkb_rules_options=altwin:swap_alt_win

# reload config
bind=SUPER+SHIFT,r,reload_config

#reload waybar
bind=CTRL+SUPER,r,spawn, /home/mat/.config/mango/scripts/mango-waybar-restart.sh

#toggle float mode
bind=SUPER,z,spawn, /home/mat/.config/mango/scripts/mango-toggle-float.sh

# menu, terminal, and apps
#bind=SUPER,space,spawn,wmenu-run -il 10
bind=SUPER,space,spawn,rofi -show drun
bind=SUPER,Return,spawn,foot
bind=SUPER+SHIFT,Return,spawn,alacritty
bind=SUPER,b,spawn,firefox
bind=SUPER,e,spawn,thunar
bind=SUPER+SHIFT,e,spawn,foot -e yazi
bind=SUPER,t,spawn,foot -e btop
bind=SUPER,p,spawn,hyprpicker -a -n

# screenshots
bind=SUPER,code:107,spawn,/home/mat/.config/mango/scripts/snip.sh

# exit
bind=SUPER+SHIFT,m,quit
bind=SUPER,q,killclient,

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

# swap window
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverlay,
bind=ALT,backslash,togglefloating,
bind=SUPER,f,togglemaximizescreen,
bind=SUPER+SHIFT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverview,
bind=SUPER+SHIFT,I,restore_minimized
bind=ALT,z,toggle_scratchpad

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=SUPER,r,switch_proportion_preset,

# switch layout
bind=SUPER,code:49,switch_layout
# ADD KEYBINDS HERE FOR SUPER+F-KEYS for specific layouts

# tag switch
bind=SUPER,Left,viewtoleft,0
bind=CTRL,Left,viewtoleft_have_client,0
bind=SUPER,Right,viewtoright,0
bind=CTRL,Right,viewtoright_have_client,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# monitor switch
bind=alt+shift,Left,focusmon,left
bind=alt+shift,Right,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right

# gaps
bind=ALT+SHIFT,code:21,incgaps,1
bind=ALT+SHIFT,code:20,incgaps,-1
bind=ALT+SHIFT,g,togglegaps

# movewin
#bind=CTRL+SHIFT,Up,movewin,+0,-50
#bind=CTRL+SHIFT,Down,movewin,+0,+50
#bind=CTRL+SHIFT,Left,movewin,-50,+0
#bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
bind=SUPER,code:20,resizewin,-50,+0
bind=SUPER,code:21,resizewin,+50,+0
bind=SUPER+SHIFT,code:20,resizewin,+0,+50
bind=SUPER+SHIFT,code:21,resizewin,+0,-50

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
