# Mango Layout & Layer Rules

# circle layout setting
circle_layout=tile,scroller,grid,center_tile

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
#tagrule=id:1,layout_name:scroller
#tagrule=id:2,layout_name:scroller
#tagrule=id:3,layout_name:tile
#tagrule=id:4,layout_name:tile
#tagrule=id:5,layout_name:tile
#tagrule=id:6,layout_name:tile
#tagrule=id:7,layout_name:tile
#tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:scroller

# layer rule
#layerrule=animation_type_open:zoom,layer_name:rofi
#layerrule=animation_type_close:zoom,layer_name:rofi

# Scroller Layout Setting
scroller_structs=10
scroller_default_proportion=0.50
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=0
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.25,0.33,0.5,0.66,1.0

# Master-Stack Layout Setting
new_is_master=0
default_mfact=0.55
default_nmaster=1
smartgaps=0
center_master_overspread=0 #(Center Tile)
center_when_single_stack=1 #(Center Tile)
