# More option see https://github.com/DreamMaoMao/mango/wiki/

source=~/.config/mango/mango-config-bindings.conf
source=~/.config/mango/mango-config-colors.conf
source=~/.config/mango/mango-config-io.conf
source=~/.config/mango/mango-config-layout.conf
source=~/.config/mango/mango-config-looknfeel.conf

# Autostart Script
exec-once=~/.config/mango/mango-autostart.sh

#exec=swaybg -i ~/.config/_themes/_current/background -m fill >/dev/null 2>&1 &
exec=swaybg -i ~/walls/cp77-8.png -m fit >/dev/null 2>&1 &

#setting float mode
source = ./mango-float.conf


# Overrides
# (any settings below this point will override corresponding settings from above)
