# Need to test what settings should be set by default vs what should be handled 
# by the theme.


# Sourcing portions of the hyprland.conf file
source = /home/$USER/.config/hypr/hyprland/looknfeel.conf
source = /home/$USER/.config/hypr/hyprland/io.conf
source = /home/$USER/.config/hypr/hyprland/bindings.conf


#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = hyprctl dispatch workspace 1
exec-once = uwsm app -- hyprpaper       #Wallpaper
exec-once = uwsm app -- waybar
exec-once = uwsm app -- swww-daemon
exec-once = uwsm app -- pypr
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- swaync
exec-once = uwsm app -- swaync-client -df
exec-once = uwsm app -- swaybg -i ~/wallpapers/dream-2.png -m fill

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Force all apps to use Wayland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
env = XDG_SESSION_TYPE,wayland

# Allow better support for screen sharing (Google Meet, Discord, etc)
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

# Use XCompose file
env = XCOMPOSEFILE,~/.XCompose

# Don't show update on first launch
ecosystem {
  no_update_news = true
}


##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Just a dash of opacity by default (Omarchy)
# windowrule = opacity 0.97 0.9, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# App-specific tweaks (Omarchy)
source = ~/.config/hypr/apps/terminals.conf
source = ~/.config/hypr/apps/system.conf
source = ~/.config/hypr/apps/browser.conf
source = ~/.config/hypr/apps/localsend.conf
source = ~/.config/hypr/apps/pip.conf
source = ~/.config/hypr/apps/qemu.conf
source = ~/.config/hypr/apps/steam.conf
source = ~/.config/hypr/apps/walker.conf
source = ~/.config/hypr/apps/1password.conf
source = ~/.config/hypr/apps/bitwarden.conf
source = ~/.config/hypr/apps/hyprshot.conf
#source = ~/.config/hypr/apps/jetbrains.conf
source = ~/.config/hypr/apps/retroarch.conf
source = ~/.config/hypr/apps/webcam-overlay.conf
source = ~/.config/hypr/apps/wine.conf
source = ~/.config/hypr/apps/transparency.conf



