
# io.conf
# for setting input/output Hyprland configurations.

################
### MONITORS ###
################

monitor=,preferred,auto,auto

monitor = DP-3, 3440x1440@143.97Hz, 0x0

monitor = DP-1, 2560x1440@165.00Hz, auto-right

######################
### DISPLAY TABLET ###
######################

# input the display tablet info

################
###   MOUSE  ###
################

#mouse stuff
