
# io.conf
# for setting input/output Hyprland configurations.

################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = DP-3, 3440x1440@143.97, 0x0, 1
monitor = DP-1, 2560x1440@165, auto-right, 1

monitor=,preferred,auto,auto

xwayland {
  force_zero_scaling = true
}


#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {

    ################
    ##  KEYBOARD  ##
    ################
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = altwin:swap_alt_win
    kb_rules =

    # Change speed of keyboard repeat
    repeat_rate = 40
    repeat_delay = 600

    # Start with numlock on by default
    numlock_by_default = true


    ################
    ##   MOUSE    ##
    ################
    follow_mouse = 2  #1=hover2focus,2=click2focus,3=separate mouse/kb focus,0=mouse-never-impact-focus
    sensitivity = 1.0 # -1.0 - 1.0, 0 means no modification.


    ################
    ##  TRACKPAD  ##
    ################
    touchpad {
        natural_scroll = false
    }
}

# https://wiki.hypr.land/Configuring/Variables/#cursor
cursor {
    hide_on_key_press = true
}


#####################
##  INPUT DISPLAY  ##
#####################

# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = ugtablet-artist-pro-24-(gen2)-pen
    output = DP-1 #input from tablet is displayed on this output (same tablet as input)
}
