[colors]
#background=fdf6e3ff
#background=fdf6e3ff
# text=657b83ff
# message=657b83ff
# prompt=586e75ff
# placeholder=93a1a1ff
# input=657b83ff
# match=cb4b16ff
# selection=eee8d5ff
# selection-text=586e75ff
# selection-match=cb4b16ff
# counter=93a1a1ff
# border=002b36ff

[border]
# width=1
# radius=10
