# Opacity overrides for video streaming sites.
windowrule = opacity 1 override 1 override, title:.*Apple TV.*
windowrule = opacity 1 override 1 override, title:.*Netflix.*
windowrule = opacity 1 override 1 override, title:.*HBO Max.*
windowrule = opacity 1 override 1 override, title:.*Hulu.*
windowrule = opacity 1 override 1 override, title:.*YouTube.*
