$activeBorderColor = rgb(f2fcff)
$activeShadowColor = rgb(6fb8e3)
$inactiveBorderColor = rgba(30486099)
$inactiveShadowColor = rgba(30486077)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
    gaps_in = 8
    gaps_out = 16
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    shadow {
      enabled = true
      range = 16
      render_power = 4
      color = $activeShadowColor
      color_inactive = $inactiveShadowColor
    }
}
