# Disable mouse focus (see https://github.com/basecamp/omarchy/pull/5183#issuecomment-4189299971)
windowrule {
    name = jetbrains-focus
    no_follow_mouse = on
    match:class = ^(jetbrains-.*)$
}
