############################################
##
##
##            theme/hyprdak
##
##
############################################

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 13

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.65


[colors]

[colors.normal]
black   = "#72696a"
red = "#ff1100"
green = "#00ff90"
yellow = "#eeff00"
blue = "#006fff"
magenta = "#ff006f"
cyan = "#00c3d1"
white = "#f0f0e9"

[colors.bright]
black = "#948a8b"
red     = "#FF003C"
green   = "#6eff00"
yellow  = "#FCEE09"
blue    = "#4a7aff"
magenta = "#ff00ee"
cyan    = "#00f0ff"
white   = "#FAFAFA"

[colors.cursor]
cursor = '#00f0ff'
text = '#050a0e'

[colors.primary]
background = '#050A0E'
foreground = '#00C3D1'

[colors.selection]
background = '#fcee09'
text = '#050a0e'



[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Underline"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
#bindings = [
#{ key = "F11", action = "ToggleFullscreen" }
#]

[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[general]
live_config_reload = true
working_directory = "None"
