
accent = "#ff8894"
cursor = "#d0d8e7"
foreground = "#d0d8e7"
background = "#0c070f"
panel_background = "#1a1220"
selection_foreground = "#d0d8e7"
selection_background = "#48141c"

color0 = "#1b1f27"
color1 = "#fd8a8d"
color2 = "#42cd9a"
color3 = "#daa932"
color4 = "#89b0ff"
color5 = "#ea8cce"
color6 = "#00ccbd"
color7 = "#c0c4cc"
color8 = "#2e333b"
color9 = "#ffb4b3"
color10 = "#62e7b3"
color11 = "#f5c351"
color12 = "#b0cbff"
color13 = "#ffaae5"
color14 = "#41e6d7"
color15 = "#dadee6"
