# Mango Theme Colors

#colors
# format: 0xRRGGBBff (final ff is full opacity)

#bordercolor=0x444444ff
#focuscolor=0xc9b890ff

shadowscolor = 0x000000ff
rootcolor = 0x14121cff
bordercolor = 0x948da5ff
focuscolor = 0x0db9d7ff
maximizescreencolor = 0x9acbfaff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xcdbdffff
globalcolor = 0x004b74ff
overlaycolor = 0x0a4a72ff
