# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x14121cff
bordercolor = 0x948da5ff
focuscolor = 0x94ccffff
maximizescreencolor = 0x9acbfaff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xcdbdffff
globalcolor = 0x004b74ff
overlaycolor = 0x0a4a72ff
